Traceback (most recent call last):
  File "plot_gt_kitti.py", line 72, in <module>
    main(args)
  File "plot_gt_kitti.py", line 38, in main
    with open(point_cloud, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/multiview/3d-count/Kitti/training/velodyne/000142.bin'