2022-12-27 22:34:10,474 INFO    MainThread:23660 [internal.py:wandb_internal():92] W&B internal server running at pid: 23660, started at: 2022-12-27 22:34:10.473782
2022-12-27 22:34:10,475 INFO    WriterThread:23660 [datastore.py:open_for_write():77] open: /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/run-2f2ff59t.wandb
2022-12-27 22:34:10,476 DEBUG   SenderThread:23660 [sender.py:send():235] send: header
2022-12-27 22:34:10,476 DEBUG   SenderThread:23660 [sender.py:send():235] send: run
2022-12-27 22:34:21,998 ERROR   SenderThread:23660 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:34:21,999 ERROR   SenderThread:23660 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:34:24,294 ERROR   SenderThread:23660 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:34:24,295 ERROR   SenderThread:23660 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:34:24,295 ERROR   SenderThread:23660 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-12-27 22:34:39,407 DEBUG   HandlerThread:23660 [handler.py:handle_request():141] handle_request: shutdown
2022-12-27 22:34:39,409 INFO    HandlerThread:23660 [handler.py:finish():790] shutting down handler
2022-12-27 22:34:39,579 INFO    WriterThread:23660 [datastore.py:close():281] close: /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/run-2f2ff59t.wandb
2022-12-27 22:34:48,016 ERROR   SenderThread:23660 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:34:48,016 ERROR   SenderThread:23660 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:35:04,603 ERROR   SenderThread:23660 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:35:04,604 ERROR   SenderThread:23660 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 22:35:42,449 ERROR   SenderThread:23660 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-12-27 22:35:42,451 ERROR   SenderThread:23660 [internal_api.py:execute():145] {"error":"internal database error"}
2022-12-27 23:48:25,261 INFO    SenderThread:23660 [dir_watcher.py:__init__():169] watching files in: /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/files
2022-12-27 23:48:25,263 INFO    SenderThread:23660 [sender.py:_start_run_threads():812] run started: 2f2ff59t with start time 1672205649
2022-12-27 23:48:25,263 INFO    SenderThread:23660 [sender.py:finish():1107] shutting down sender
2022-12-27 23:48:25,264 INFO    SenderThread:23660 [dir_watcher.py:finish():283] shutting down directory watcher
2022-12-27 23:48:26,273 INFO    SenderThread:23660 [dir_watcher.py:finish():313] scan: /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/files
2022-12-27 23:48:26,274 INFO    SenderThread:23660 [dir_watcher.py:finish():327] scan save: /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/files/config.yaml config.yaml
2022-12-27 23:48:26,275 INFO    SenderThread:23660 [file_pusher.py:finish():145] shutting down file pusher
2022-12-27 23:48:26,275 INFO    SenderThread:23660 [file_pusher.py:join():150] waiting for file pusher
2022-12-27 23:48:26,906 INFO    Thread-9  :23660 [upload_job.py:push():137] Uploaded file /Users/stephennelson/Projects/Learning-Frustum-Proposals/preprocess/wandb/run-20221227_223409-2f2ff59t/files/config.yaml
2022-12-27 23:48:27,468 INFO    MainThread:23660 [internal.py:handle_exit():82] Internal process exited
