
  0%|                                                                                                                                        | 0/1 [00:00<?, ?it/s][W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
Logging model files to ./chkp/12-31-2022_22:43:38
TRAINING MODEL: regressor
Training on CPU
************* EPOCH: 1 *************
Pointnet.py
torch.Size([1, 64, 131])
torch.Size([1, 64, 131])
torch.Size([1, 64, 131])
> /Users/stephennelson/Projects/Learning-Frustum-Proposals/models/frustum_neonet.py(32)forward()
-> y_hat = self.output_head(h)

(Pdb) continue
> /Users/stephennelson/Projects/Learning-Frustum-Proposals/models/regressor.py(43)forward()
-> h = self.weights(x)

(Pdb) continue
  0%|                                                                                                                                        | 0/1 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "train_frustum_neonet.py", line 101, in <module>
    main(args)
  File "train_frustum_neonet.py", line 89, in main
    trainer.fit()
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/trainers/base_trainer.py", line 345, in fit
    y_hat = self._batch_prediction(inputs.float()).to(self.device)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/trainers/learned_frustum_trainer.py", line 54, in _batch_prediction
    y_hat = self.model(
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/models/frustum_neonet.py", line 32, in forward
    pdb.set_trace()
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/models/regressor.py", line 43, in forward
    y_hat = self.output(h)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x512 and 515x512)