/home/stephen/anaconda3/envs/detection3d/lib/python3.8/site-packages/pytorch3d/io/obj_io.py:542: UserWarning: No mtl file provided
  warnings.warn("No mtl file provided")
Traceback (most recent call last):
  File "viz_display_audit.py", line 76, in <module>
    main(args)
  File "viz_display_audit.py", line 49, in main
    img_dict = run.get_img_log(data[val]['image']['image_path'])
  File "/home/stephen/Projects/Learned-Frustum-Proposals/Thesis/wandb_utils/wandb.py", line 136, in get_img_log
    image = wandb.Image(fpath_or_list, caption=caption)
  File "/home/stephen/anaconda3/envs/detection3d/lib/python3.8/site-packages/wandb/sdk/data_types/image.py", line 151, in __init__
    self._initialize_from_path(data_or_path)
  File "/home/stephen/anaconda3/envs/detection3d/lib/python3.8/site-packages/wandb/sdk/data_types/image.py", line 245, in _initialize_from_path
    self._set_file(path, is_tmp=False)
  File "/home/stephen/anaconda3/envs/detection3d/lib/python3.8/site-packages/wandb/sdk/data_types/base_types/media.py", line 66, in _set_file
    with open(self._path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'image/000001.jpg'