Traceback (most recent call last):
  File "plot_gt_kitti.py", line 74, in <module>
    main(args)
  File "plot_gt_kitti.py", line 37, in main
    calib = Calibration(calib_filepath=calib_file)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/datasets/kitti/kitti_util.py", line 84, in __init__
    calibs = self.read_calib_file(calib_filepath)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/datasets/kitti/kitti_util.py", line 113, in read_calib_file
    key, value = line.split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)